### ISSUE TITLE
Failed to check for LOOT updates!

### ISSUE THREAD

**Issue by asifchoudhuryonline** [loot/loot#1011]
I am using Windows 10. I was using MO to mod Skyrim and using LOOT through MO it was all fine the whole day and suddenly I am getting this error: Failed to check for LOOT updates! You can check your LOOTDebugLog.txt (you can get to it through the main menu) for more information.
This is what I found: [LOOTDebugLog.txt](https://github.com/loot/loot/files/2368846/LOOTDebugLog.txt)
I retried updating through the LOOT application(without MO) but the results are same.
Here is another log I got after I enabled debug logging: [LOOTDebugLog.txt](https://github.com/loot/loot/files/2368857/LOOTDebugLog.txt)

**Comment by arthurh3535** [comment]
My LOOTDebugLog.txt mentioned that Chromium depreciated the system used for the update check, I think. So that might have to be reworked or a 'check for updates' button added for manually checking.

**Comment by WrinklyNinja** [comment]
For some reason our release build failed, which is probably why. The Chromium deprecation message is unrelated.

The release is fixed now, do either of you still experience the issue?

**Comment by arthurh3535** [comment]
Seems fine now.

**Comment by CptMcSplody** [comment]
@WrinklyNinja I had the warning on first start up, it went away when I ran manual update of master list.

**Comment by WrinklyNinja** [comment]
In that case I'll close this.

**Comment by asifchoudhuryonline** [comment]
Its fie now, thanks @WrinklyNinja

**Comment by pStyl3** [comment]
I think this issue is not resolved just yet. With a fresh install of LOOT 0.13.2 (deleted \%localappdata%\LOOT beforehand) the aforementioned error message *will* be displayed. It's true that it goes away once the user updates her/his masterlist, however it isn't good that an error will be displayed upon installing LOOT fresh. This needs to be fixed, unless we want to be bombarded with bug reports.

**Comment by Remmiie** [comment]
I also am having this same exact same issue.

**Comment by WrinklyNinja** [comment]
Fixed in 605ff7b676270229291f823e9ddbb9bbd4e07b8f, I'll tag a new release shortly.

**Comment by mhmdemad** [comment]
It occurs sometimes, but after a few MO2 restart fixed it.

**Comment by SkyeRangerDelta** [comment]
Hello,

I've been running LOOT for a while now, mainly out of MO with this problem. I've ignored it for a few releases (yes, it has persisted through all the way until the latest (0.13.6) which I've downloaded today) and I still have the problem. If I'm reading through this correctly, the errors saying something from Chromium console can be ignored safely, but I've got nothing else to go off of.

Debug log:
`[15:35:27.843986] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 5658: Failed to check for LOOT updates, details: Failed to fetch`

The problems occurs both inside and outside of MO.

Debugging log shows the same errors. Could this be a firewall problem from a security software or something? I use Git for some of my own personal projects, I don't think I'd have problems pulling/pushing info from a repo.

I'd be appreciative of some help.

**Comment by SkyeRangerDelta** [comment]
> 
> 
> Hello,
> 
> I've been running LOOT for a while now, mainly out of MO with this problem. I've ignored it for a few releases (yes, it has persisted through all the way until the latest (0.13.6) which I've downloaded today) and I still have the problem. If I'm reading through this correctly, the errors saying something from Chromium console can be ignored safely, but I've got nothing else to go off of.
> 
> Debug log:
> `[15:35:27.843986] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 5658: Failed to check for LOOT updates, details: Failed to fetch`
> 
> The problems occurs both inside and outside of MO.
> 
> Debugging log shows the same errors. Could this be a firewall problem from a security software or something? I use Git for some of my own personal projects, I don't think I'd have problems pulling/pushing info from a repo.
> 
> I'd be appreciative of some help.

I hate it when I do this, but thinking through my post - I fixed the problem. It was my security software blocking the updates/connections.
