### ISSUE TITLE
N/A: No Masterlist Present (0.12.4)

### ISSUE THREAD

**Issue by MemeChaser69** [loot/loot#903]
Getting "N/A: No masterlist present". Yes, I've done everything your troubleshooting page tells me to do. Everything I need is up-to-date and/or installed. Debug File attached. It said Chromium, so I uninstalled Google Chrome.
[LOOTDebugLogCensored.txt](https://github.com/loot/loot/files/1773501/LOOTDebugLogCensored.txt)

**Comment by WrinklyNinja** [comment]
> It said Chromium, so I uninstalled Google Chrome.

Well, you didn't need to do that... LOOT uses Chromium internally, it's nothing to do with Chrome.

Have you tried updating the masterlist? There's nothing in your log to suggest you did, and generally if LOOT's saying there's no masterlist present, you just need to run the masterlist update.

**Comment by shinnman** [comment]
HITTING THE MASTERLIST DOWNLOAD BUTTON CAUSES AN ERROR FOR ME

**Comment by Beetus** [comment]
Hey Wrinkly, love LOOT and appreciate all the work.

I've also had these same issues that I've seen everyone else have, so I tried the manual method by disabling autoupdate in settings, then dling and adding the SkyrimSE masterlist.yaml then tried sorting.  But then it says "unknown: git repository missing" and doesn't seem to make any positive changes to my load order (mostly because I keep getting CTD's when I load my game...)  Is there any steps I missed or anything else I can do?  Thank you in advance!

p.s.  I should note I have no programming or coding knowledge, just a hobbyist.  So I really do appreciate your hard work  :)

**Comment by WrinklyNinja** [comment]
> HITTING THE MASTERLIST DOWNLOAD BUTTON CAUSES AN ERROR FOR ME

PLEASE SEE [HOW TO REPORT ISSUES HELPFULLY](http://loot.github.io/docs/help/How-To-Report-Issues-Helpfully.html).

> Is there any steps I missed or anything else I can do? Thank you in advance!

`unknown: git repository missing` is expected, it's just saying that LOOT can't tell what version of the masterlist you're using because you downloaded it manually. The EasyFix linked to in #882 seems to work for just about everyone, so try that and re-enable masterlist autoupdate. I tend not to debug specific load order issues because it's been so long since I played any of the games, if LOOT is working you're better off trying to get load order help by posting in a modding forum somewhere.

**Comment by Beetus** [comment]
Oh I wasn't expecting specific load order help, I just wasn't sure if that error meant that LOOT wasn't doing it's thing.  Thank you very much for the reply, will try your suggestion!

**Comment by Beetus** [comment]
Fix worked, thanks!

**Comment by dubirdrs** [comment]
Ok, running the latest LOOT through the latest MO.  Getting the same error as everyone else.  Did a manual download of the Skyrim master list, and if I start LOOT on its own, I don't have the error issue.  Running it through MO gives me that error, even with update turned off and the actual list saved in the LOOT/Skyrim folder.

**Comment by rodeowearden** [comment]
I created an account just so I could comment on this thread.  The easy fix worked for me as well.  Thanks to everyone who contributed information, and special thanks to @WrinklyNinja for all your hard work!

**Comment by saveed4eva** [comment]
not working im fucken pissed off can i roll this shit back been fucking with this shit for 3 days now   
HOW DO I FIX THE FUCKER   ???  WIN 7

**Comment by pStyl3** [comment]
@saveed4eva Please see [How To Report Issues Helpfully](https://loot.github.io/docs/help/How-To-Report-Issues-Helpfully.html). Also, watch your language, otherwise you'll be shown the door.

**Comment by saveed4eva** [comment]
you destroyed my whole game ?  and now loot dont work hours and hours of
modding gone  can i roll it back or what ?

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by TheWeezel** [comment]
So I just started up and had this same issue.  I have not fixed the issue but I have gotten it working.  It looks like the system deletes the existing masterlist.yaml when it is trying to update and then I think something is going wrong trying to get to the github repository where it is expecting the masterlist.yaml.  I think this because under the General information section of Loot bothe Masterlist Revision and Masterlist Date say "Unknown:Git repository missing". 

As a break-fix I first turned off the autoupdate of the Masterlist, then I went to https://github.com/loot/fallout4/blob/v0.10/masterlist.yaml and downloaded the raw of the file (https://raw.githubusercontent.com/loot/fallout4/v0.10/masterlist.yaml) and put that in my %LocalAppData%\LOOT\Fallout4

When I went to the FAQ going through it I found a location for the Skyrim Masterlist.yaml and when I just changed the Skyrim to Fallout4 (https://raw.githubusercontent.com/loot/fallout4/master/masterlist.yaml) it directed me to a 404.  I am wondering if at some point the Github path for the store got changed and if it is hardcoded into the application then that seems like it could cause the issue.

Of course I could be totally off base but just wanted to give what I had found.  My log files are consistent with everyone else's sadly.

**Comment by WrinklyNinja** [comment]
> When I went to the FAQ going through it I found a location for the Skyrim Masterlist.yaml and when I just changed the Skyrim to Fallout4 (https://raw.githubusercontent.com/loot/fallout4/master/masterlist.yaml) it directed me to a 404. I am wondering if at some point the Github path for the store got changed and if it is hardcoded into the application then that seems like it could cause the issue.

The master branch holds masterlists used by LOOT v0.6, which didn't support Fallout 4, so its masterlist repo doesn't have a master branch. Use the v0.10 branch instead: https://raw.githubusercontent.com/loot/fallout4/v0.10/masterlist.yaml

**Comment by TheWeezel** [comment]
> The master branch holds masterlists used by LOOT v0.6, which didn't support Fallout 4, so its masterlist repo doesn't have a master branch. Use the v0.10 branch instead: https://raw.githubusercontent.com/loot/fallout4/v0.10/masterlist.yaml

Ah.  Well if that is for an older version then perhaps an update to the FAQ is in order to allow people to go to the right places if there is an issue where people need to manually update the masterlist.

**Comment by WrinklyNinja** [comment]
> Ah. Well if that is for an older version then perhaps an update to the FAQ is in order to allow people to go to the right places if there is an issue where people need to manually update the masterlist.

Done, thanks.

**Comment by TheWeezel** [comment]
> Done, thanks.

No, thank you.  I'm old enough to remember having to manually order my mods.  I could probably still do it but having this as an option helps immensely.

I am testing the use of the TLS 1.1/1.2 Enabling fix.  I feel that will work.  Looking at the Github cert it is using a TLS 1.2.  Sadly 1.3 still isn't out so unless they release that and systems are updated I think that the enabling of at least TLS 1.2 will be needed for the foreseeable future unless Github decides to change its cert at renewal.

**Comment by vbmdsm** [comment]
Firstly, I am lost without LOOT! I also remember manual mod ordering...

I am running Win7 Pro that I have applied the EasyFix update from Microsoft to, but with no luck.
I've downloaded the Masterfile that WN linked in another topic #882 I believe and got the repository missing message and no sorting that I could see.

I've since downloaded another Masterfile from the v0.10 branch page and now I am getting an "illegal map value" error when I run LOOT. Looking into the Masterfile, it appears that LOOT is having issues with colons (:) - if I remove the character in the message, next run LOOT moves down the Masterfile and spits out the same error message for the next colon character it comes to, and it continues to a 3rd instance also. 

However, ignoring the error message and running a Sort seems to have LOOT do a sort just fine...

I've attached log file for information.
[LOOTDebugLog.txt](https://github.com/loot/loot/files/1927801/LOOTDebugLog.txt)

**Comment by WrinklyNinja** [comment]
> I am running Win7 Pro that I have applied the EasyFix update from Microsoft to, but with no luck.

If you're using the latest LOOT release you shouldn't need to apply any fixes or manually download masterlists. Make sure you're on v0.12.5, then try updating your masterlist.

**Comment by vbmdsm** [comment]
Thanks for the reply WN...

Yes I am using LOOT 0.12.5, paired with MO 2. 

I applied the EasyFix update as it was part of the solutions being given in topic #882. 

But alas, I do seem to need to try these manual actions as LOOT on my system is not functioning as expected, or as previous versions have.

**Comment by WrinklyNinja** [comment]
Running LOOT through Mod Organiser is unsupported, as most issues reported by Mod Organiser users are caused by Mod Organiser, which I can't do anything about.

Please try to replicate your issue while running LOOT independently of Mod Organiser.

**Comment by vbmdsm** [comment]
Ok, will get back to you...

**Comment by WrinklyNinja** [comment]
You've saved a GitHub webpage and called it `masterlist.yaml`, I'm not surprised that doesn't work.

Try updating the masterlist independently of MO2.

**Comment by vbmdsm** [comment]
Well, that was a newb thing to do wasn't it...

Your suggestion did the trick and all appears to be functioning as expected.

Many thanks for the assist WrinklyNinja.
